site_name: DCS F-100D Manual
plugins:
    - search
    #- offline
    #- with-pdf:
    #    headless_chrome_path: C:/Program Files/Google/Chrome/Application/chrome.exe
    #    render_js: true
    - print-site:
        print_page_title: 'Manual'
        enumerate_headings: false
        toc_depth: 1

theme:
  name: readthedocs
  custom_dir: 'custom_theme/'  # or any other theme
  features:
    - navigation.instant

docs_dir: src

nav:
    - Introduction:
      - Overview: ./Introduction/introduction.md
    - General Systems:
      - Hydraulics:
        - Introduction: ./Hydraulics/introduction.md
        - Utility: ./Hydraulics/utility.md
    - Defensive Systems:
      - AN/APR-25 RHAW: ./RHAW/RHAW.md
    - Weapon Systems:
      - Armament Control Panels: ./Weapon System/armament-control-panels.md
      - Basic Armament Control Circuitry: ./Weapon System/basic-armament-control-circuitry.md
      - Aircraft Weapons Release System: ./Weapon System/aircraft-weapons-release-system.md
      - A-4 Gunsight: ./Weapon System/a-4-gunsight.md
      - AIM-9 Sidewinder: ./Weapon System/aim-9-sidewinder.md

    - Procedures:
      - Weapons Employment:
        - Manual Delivery: ./Weapon System/Procedures/manual-delivery.md
        - Sidewinders: ./Weapon System/Procedures/sidewinder.md

    