site_name: DCS F-100D Manual
plugins:
    - search
    #- offline
    #- with-pdf:
    #    headless_chrome_path: C:/Program Files/Google/Chrome/Application/chrome.exe
    #    render_js: true
    - print-site:
        print_page_title: 'Manual'
        enumerate_headings: false
        toc_depth: 1

theme:
  name: readthedocs
  custom_dir: 'custom_theme/'  # or any other theme
  features:
    - navigation.instant

docs_dir: src
use_directory_urls: false

nav:
    - 'index.md'
    - Introduction:
      - Overview: ./Introduction/introduction.md
      - Special Options: ./Introduction/special-options.md
      - Research Series: ./Introduction/research-series.md
      - Official Soundtrack: ./Introduction/official-soundtrack.md
    - General Systems:
      - Electrical: ./Electrical/electrical.md
      - Hydraulics:
        - Introduction: ./Hydraulics/introduction.md
        - Utility: ./Hydraulics/utility.md
      - MD-1 Oxygen Regulator: ./Oxygen System/oxygen.md
      - AN/APX-72 IFF: ./APX-72 IFF/iff.md
      - Lighting Control Panel: ./Lighting Control Panel/lighting-control-panel.md
    - Navigation Systems:
      - Direction Gyro and Compass: ./DirectionGyroCompass/direction-gyro-and-compass.md
      - B-26 Navigation Computer: ./Navigation Computer/navigation-computer.md
    - Radio Systems:
        - ARC-34 UHF Command Radio: ./ARC-34 Command Radio/command-radio.md
        - ARA-50 ADF System: ./ARA-50 ADF/adf-radio.md
        - ARN-6 Radio Compass: ./ARN-6 Radio Compass/radio-compass.md
        - ARN-72 TACAN: ./ARN-72 TACAN/tacan.md
        - Seek Silence System: ./Seek Silence System/seek-silence.md 
    - Defensive Systems:
      - AN/APR-25 RHAW: ./RHAW/RHAW.md
    - Weapon Systems:
      - Introduction: ./Weapon_System/introduction.md
      - Armament Control Panels: ./Weapon_System/armament-control-panels.md
      - Basic Armament Control Circuitry: ./Weapon_System/basic-armament-control-circuitry.md
      - Aircraft Weapons Release System: ./Weapon_System/aircraft-weapons-release-system.md
      - A-4 Gunsight: ./Weapon_System/a-4-gunsight.md
      - Guns: ./Weapon_System/guns.md
      - AIM-9 Sidewinder: ./Weapon_System/aim-9-sidewinder.md
      - AIM-45 Shrike: ./Weapon_System/agm-45-shrike.md
      - AN/AJB-1 Low Altitude Bombing System: ./Weapon_System/low-altitude-bombing-system.md

    - Procedures:
      - Weapons Employment:
        - Manual Delivery: ./Weapon_System/Procedures/manual-delivery.md
        - Sidewinders: ./Weapon_System/Procedures/sidewinder.md

    